### PR TITLE
Make tokenizer less restrictive

### PR DESCRIPTION
**Pull request by Xiphoseer**
This PR includes two small changes to the tokenizer that will make it less restrictive in some cases.

1. Accept number literals that omit a value of `0` before the decimal point. For example `.5` or `.7e2` are now valid number tokens that should be interpreted as if they were `0.5` or `0.7e2` respectively. This notation is accepted by the LUA 5.1 interpreter.

2. Accept `'\r'` as normal whitespace. For example the sequence `"\r\r\n"` currently causes a syntax error while the LUA 5.1 interpreter runs it just fine.
   
   The reason for that is that the `nom` parsers `space1` and `line_ending` don't match the regex used in the LUA grammar. `nom` sees `' '` and `'\t'` as space and `"\r\n"` or `"\n"` as a line break, LUA (according to a comment in this codebase) uses `[^\S\n]` as space (which is `' '`, `'\t'`, `'\r'`, `'\u{b}'`, `\u{c}` if you don't account for unicode whitespace) and `'\n'` as line break.
   
   The changes in this PR are a minimal step in that direction, by adding `'\r'` to be handled like a space and using `tag("\n")` instead of `nom`s `line_ending` for line breaks.

### CODE REVIEW

**Comment by Kampfkarren** [comment]
Thanks for the PR! I'm going to hold off on merging this for now since there's a massive refactor PR going on right now, but this shouldn't cause any conflicts with that. Will make sure your PR works with mine. Thanks!

**Comment by Xiphoseer** [comment]
Great! Thank you for your time and good luck with the refactoring.

**Comment by Rerumu** [comment]
I looked at the code and wanted to point out the PR still doesn't support different cases in `0x`, `0X`, `e` and `E`. Hexadecimal numbers also have an optional exponent that uses `p` instead of `e`. The former issue can probably be solved using `tag_no_case`, but the latter is slightly trickier.

**Comment by Kampfkarren** [comment]
Sorry for the long delay, but the refactor is merged now if you want to take a look at this again.

**Comment by Kampfkarren** [comment]
Stale, let me know if you want to work on this again.

**Comment by Xiphoseer** [comment]
Ah, thanks for the reminder! I somehow missed your last comment and haven't worked on the project I use this for in a while.

I'll look at this and get back to you when I find the time.

I'm also a little disappointed that the performance characteristics of using this library (to process a bunch of files to JSON for syntax highlighting in a browser and possibly some analysis down the line) seems worse than my previous impl which used luaparse.js

I may end up trying whether generating JSON for this AST and rewriting my display code is much faster or whether I'll find a different library that is as complete as this one but less focused on being usable in an IDE and the associated overhead of using Arc

**Comment by Kampfkarren** [comment]
> I'm also a little disappointed that the performance characteristics of using this library (to process a bunch of files to JSON for syntax highlighting in a browser and possibly some analysis down the line) seems worse than my previous impl which used luaparse.js

Have you tried the latest version? Since you made this PR some massive optimizations have been made.

**Comment by Xiphoseer** [comment]
> Have you tried the latest version? Since you made this PR some massive optimizations have been made.

I have not, which is why I'll happily give it a try when I find the time and energy. It was more to hint as to why I may not follow through with using this lib.

My current project is mostly glue code to convince miniserde to produce a luaparse AST from this lib and that really isn't satisfying to write.

**Comment by Xiphoseer** [comment]
I have now tried out the current version (by including the latest commit as a git dependency) and I can confirm that the performance is much better now.

I still had issues with the tokenizer rejecting some random misplaced `\r` characters in the scripts I'm working with. I chose to just fix the few cases on my end, but ideally, the tokenizer would confirm to the LUA spec. If you want, I can extract those changes from this PR and send a new one, just for line endings.

**Comment by Kampfkarren** [comment]
> I still had issues with the tokenizer rejecting some random misplaced \r characters in the scripts I'm working with.

I got word of this too, I hopefully fixed it in #72.

In the meantime, #71 was merged. Can you make sure that it doesn't supersede what you did here?

**Comment by Xiphoseer** [comment]
Yes, I've seen that #71 was merged and it resolves the numbers part of this PR. Sorry that I didn't notice the existing issue for that when I created mine.

As far as I can tell, #72 only touches tests, not the tokenizer code. I've seen one recent PR for CRLF, but the issue I'm facing is single CRs as newlines in some places, not a CRLF.

LUA treats those as simple whitespace and only really cares about the LF to break lines. The tokenizer in this lib just rejects these files with the code in this repo (tested just before my last comment was made)

**Comment by Kampfkarren** [comment]
Definitely file an issue for those, or even better a pull request to fix it. Files with lone `CR`s are rare to my knowledge, so this is the first I'm hearing about it!

**Pull request closed without merging**
